/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Recipe, Component } from './types';

export const PRESET_RECIPES: Recipe[] = [
  {id:'mon-l',preset:true,day:'Mon',slot:'Lunch',name:'Chimichurri chicken bowl',desc:'Blackened chicken breast over cauliflower rice with house chimichurri',emoji:'🍗',components:['blackened-chicken','cauli-rice','chimichurri'],ingredients:[{name:'Chicken breast',amount:7,unit:'oz',pricePerUnit:0.25},{name:'Cauliflower rice',amount:1,unit:'cup',pricePerUnit:0.85},{name:'Chimichurri',amount:3,unit:'tbsp',pricePerUnit:0.18},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:1.05}],assembly:['Slice rested blackened chicken against the grain','Plate over warm cauliflower rice','Drizzle generously with chimichurri']},
  {id:'mon-d',preset:true,day:'Mon',slot:'Dinner',name:'Sirloin + Dijon + broccoli',desc:'Seared sirloin with creamy Dijon & roasted broccoli',emoji:'🥩',components:['sirloin','broc-mush','dijon'],ingredients:[{name:'Sirloin steak',amount:6,unit:'oz',pricePerUnit:0.56},{name:'Broccoli & mushrooms',amount:1,unit:'cup',pricePerUnit:1.15},{name:'Creamy Dijon sauce',amount:3,unit:'tbsp',pricePerUnit:0.30},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.95}],assembly:['Slice rested sirloin against the grain','Plate with roasted broccoli & mushrooms','Spoon warm Dijon sauce over steak']},
  {id:'tue-l',preset:true,day:'Tue',slot:'Lunch',name:'Turkey taco bowl',desc:'Seasoned ground turkey over cauliflower rice with pico de gallo',emoji:'🫙',components:['turkey-taco','cauli-rice','pico'],ingredients:[{name:'Ground turkey',amount:5,unit:'oz',pricePerUnit:0.25},{name:'Cauliflower rice',amount:1,unit:'cup',pricePerUnit:0.85},{name:'Pico de gallo',amount:0.25,unit:'cup',pricePerUnit:1.80},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.90}],assembly:['Warm cauliflower rice as base','Top with taco-seasoned turkey','Finish with fresh pico de gallo']},
  {id:'tue-d',preset:true,day:'Tue',slot:'Dinner',name:'Blackened salmon + creamed kale',desc:'Cast iron salmon with creamed kale & garlic butter',emoji:'🐟',components:['blackened-salmon','creamed-kale','garlic-butter'],ingredients:[{name:'Salmon',amount:6,unit:'oz',pricePerUnit:0.44},{name:'Creamed kale & spinach',amount:1,unit:'cup',pricePerUnit:1.45},{name:'Garlic butter sauce',amount:2,unit:'tbsp',pricePerUnit:0.33},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.95}],assembly:['Plate creamed kale as base','Top with blackened salmon','Drizzle with warm garlic butter']},
  {id:'wed-l',preset:true,day:'Wed',slot:'Lunch',name:'Salmon + spinach & lemon herb',desc:'Cold salmon over fresh spinach with lemon herb dressing',emoji:'🐟',components:['blackened-salmon','fresh-spinach','lemon-herb'],ingredients:[{name:'Salmon',amount:6,unit:'oz',pricePerUnit:0.44},{name:'Fresh spinach',amount:2,unit:'cup',pricePerUnit:0.38},{name:'Lemon herb dressing',amount:2,unit:'tbsp',pricePerUnit:0.20},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.60}],assembly:['Bed of fresh spinach in container','Top with cold salmon flaked into chunks','Serve with dressing on the side']},
  {id:'wed-d',preset:true,day:'Wed',slot:'Dinner',name:'Herb chicken + roasted veggies',desc:'Herb-crusted chicken with roasted zucchini & peppers',emoji:'🍗',components:['herb-chicken','zucc-pep','herb-oil'],ingredients:[{name:'Chicken breast',amount:7,unit:'oz',pricePerUnit:0.25},{name:'Zucchini & peppers',amount:1,unit:'cup',pricePerUnit:1.10},{name:'Herb oil drizzle',amount:1,unit:'tbsp',pricePerUnit:0.35},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.60}],assembly:['Plate roasted veggies as base','Slice and fan herb chicken on top','Drizzle with herb oil']},
  {id:'thu-l',preset:true,day:'Thu',slot:'Lunch',name:'Steak + creamy tomato + mushrooms',desc:'Sliced sirloin with creamy tomato basil & mushrooms',emoji:'🥩',components:['sirloin','roasted-mushrooms','tomato-basil'],ingredients:[{name:'Sirloin steak',amount:6,unit:'oz',pricePerUnit:0.56},{name:'Roasted mushrooms',amount:0.75,unit:'cup',pricePerUnit:1.00},{name:'Creamy tomato basil',amount:3,unit:'tbsp',pricePerUnit:0.32},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.90}],assembly:['Plate roasted mushrooms','Fan sliced sirloin over mushrooms','Spoon warm tomato basil sauce on top']},
  {id:'thu-d',preset:true,day:'Thu',slot:'Dinner',name:'Garlic shrimp stir-fry + bok choy',desc:'Sautéed shrimp with garlic butter over bok choy',emoji:'🦐',components:['sauteed-shrimp','bok-choy','garlic-butter'],ingredients:[{name:'Shrimp',amount:6,unit:'oz',pricePerUnit:0.56},{name:'Bok choy',amount:1,unit:'ea',pricePerUnit:0.75},{name:'Garlic butter sauce',amount:2,unit:'tbsp',pricePerUnit:0.33},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:1.00}],assembly:['Plate sautéed bok choy','Top with garlic shrimp','Drizzle with extra garlic butter']},
  {id:'fri-l',preset:true,day:'Fri',slot:'Lunch',name:'Shrimp & zucchini noodle bowl',desc:'Seasoned shrimp over spiralized zucchini with lemon herb',emoji:'🦐',components:['sauteed-shrimp','zucc-noodle','lemon-herb'],ingredients:[{name:'Shrimp',amount:6,unit:'oz',pricePerUnit:0.56},{name:'Zucchini noodles',amount:1,unit:'ea',pricePerUnit:0.65},{name:'Lemon herb dressing',amount:2,unit:'tbsp',pricePerUnit:0.20},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.60}],assembly:['Bed of zucchini noodles','Top with warm shrimp','Drizzle with lemon herb dressing']},
  {id:'fri-d',preset:true,day:'Fri',slot:'Dinner',name:'Chimichurri chicken thighs + zucchini',desc:'Juicy chicken thighs with chimichurri & roasted zucchini',emoji:'🍗',components:['chimi-thighs','zucc-pep','chimichurri'],ingredients:[{name:'Chicken thigh',amount:1,unit:'ea',pricePerUnit:0.65},{name:'Zucchini & peppers',amount:0.5,unit:'cup',pricePerUnit:0.55},{name:'Chimichurri',amount:3,unit:'tbsp',pricePerUnit:0.18},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.90}],assembly:['Plate roasted zucchini & peppers','Add chicken thigh','Drizzle with chimichurri']},
  {id:'sat-l',preset:true,day:'Sat',slot:'Lunch',name:'Chicken + roasted veggie bowl',desc:'Herb chicken with seasonal roasted vegetables',emoji:'🍗',components:['herb-chicken','zucc-pep','herb-oil'],ingredients:[{name:'Chicken breast',amount:7,unit:'oz',pricePerUnit:0.25},{name:'Zucchini & peppers',amount:1,unit:'cup',pricePerUnit:1.10},{name:'Herb oil drizzle',amount:1,unit:'tbsp',pricePerUnit:0.35},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.60}],assembly:['Base of roasted veggies','Sliced herb chicken on top','Finish with herb oil drizzle']},
  {id:'sat-d',preset:true,day:'Sat',slot:'Dinner',name:'Sirloin + creamy tomato & spinach',desc:'Sliced sirloin with creamy tomato over creamed spinach',emoji:'🥩',components:['sirloin','creamed-kale','tomato-basil'],ingredients:[{name:'Sirloin steak',amount:6,unit:'oz',pricePerUnit:0.56},{name:'Creamed kale & spinach',amount:1,unit:'cup',pricePerUnit:1.45},{name:'Creamy tomato basil',amount:3,unit:'tbsp',pricePerUnit:0.32},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.90}],assembly:['Creamed spinach as base','Fan sliced sirloin on top','Spoon warm tomato basil sauce over']},
  {id:'sun-l',preset:true,day:'Sun',slot:'Lunch',name:'Turkey stuffed pepper + salad',desc:'Taco-spiced turkey in a roasted bell pepper',emoji:'🫑',components:['turkey-taco','stuffed-pepper','pico'],ingredients:[{name:'Ground turkey',amount:5,unit:'oz',pricePerUnit:0.25},{name:'Bell pepper + salad',amount:1,unit:'ea',pricePerUnit:1.50},{name:'Pico de gallo',amount:0.25,unit:'cup',pricePerUnit:1.80},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.95}],assembly:['Stuff pepper with cooked turkey taco meat','Bake as directed in stuffed pepper component','Serve with side salad and pico de gallo']},
  {id:'sun-d',preset:true,day:'Sun',slot:'Dinner',name:'Turkey meatballs + ratatouille',desc:'Herb turkey meatballs with roasted ratatouille',emoji:'🍅',components:['turkey-meatballs','ratatouille','herb-oil'],ingredients:[{name:'Ground turkey',amount:5,unit:'oz',pricePerUnit:0.25},{name:'Ratatouille veggies',amount:1,unit:'cup',pricePerUnit:1.00},{name:'Herb oil drizzle',amount:1,unit:'tbsp',pricePerUnit:0.35},{name:'Overhead',amount:1,unit:'ea',pricePerUnit:0.60}],assembly:['Plate ratatouille as base','Arrange meatballs on top','Finish with herb oil drizzle']},
];

export const COMPONENTS: Record<string, Component> = {
  'blackened-chicken': {name:'Blackened chicken breast',emoji:'🍗',category:'protein',yield:'1 serving',ingredients:[{name:'Chicken breast',amount:7,unit:'oz'},{name:'Avocado oil',amount:1,unit:'tsp'},{name:'Smoked paprika',amount:1,unit:'tsp'},{name:'Garlic powder',amount:0.5,unit:'tsp'},{name:'Onion powder',amount:0.25,unit:'tsp'},{name:'Cayenne',amount:0.25,unit:'tsp'},{name:'Thyme',amount:0.25,unit:'tsp'},{name:'Salt',amount:0.5,unit:'tsp'},{name:'Black pepper',amount:0.25,unit:'tsp'}],steps:['Mix spices into blackening blend','Pat chicken dry, brush with oil, coat all sides in spice blend','Sear in cast iron over high heat 3–4 min per side until deep crust forms','Finish in 400°F oven 8–10 min until 165°F internal','Rest 5 min before slicing'],storage:'Keeps 3–4 days refrigerated. Reheats best in 300°F oven for 6 min.',utensils:['Cast iron pan','Oven','Meat thermometer']},
  'chimi-thighs': {name:'Chimichurri chicken thighs',emoji:'🍗',category:'protein',yield:'1 serving',ingredients:[{name:'Chicken thigh, bone-in',amount:1,unit:'ea'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'},{name:'Black pepper',amount:0.125,unit:'tsp'},{name:'Garlic powder',amount:0.25,unit:'tsp'}],steps:['Pat dry, season all sides','Hot pan with oil, skin-side down 5–6 min','Flip, cook 4 min more','Transfer to 400°F oven for 15 min until 165°F','Rest 5 min, drizzle with chimichurri to serve'],storage:'Keeps 3–4 days. Reheat gently to preserve crispy skin.',utensils:['Large skillet','Oven','Meat thermometer']},
  'herb-chicken': {name:'Herb chicken breast',emoji:'🍗',category:'protein',yield:'1 serving',ingredients:[{name:'Chicken breast',amount:7,unit:'oz'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Italian herbs',amount:1,unit:'tsp'},{name:'Garlic powder',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.5,unit:'tsp'},{name:'Black pepper',amount:0.25,unit:'tsp'}],steps:['Pat chicken dry, season all sides','Sear in oil 3–4 min per side until golden','Finish in 400°F oven 8–10 min until 165°F','Rest 5 min, slice against the grain'],storage:'Keeps 3–4 days refrigerated.',utensils:['Skillet','Oven','Meat thermometer']},
  'sirloin': {name:'Seared sirloin steak',emoji:'🥩',category:'protein',yield:'1 serving',ingredients:[{name:'Top sirloin steak (1–1.25" thick)',amount:6,unit:'oz'},{name:'Avocado oil',amount:1,unit:'tsp'},{name:'Butter',amount:1,unit:'tsp'},{name:'Garlic, smashed',amount:1,unit:'clove'},{name:'Fresh thyme',amount:1,unit:'sprig'},{name:'Salt',amount:0.5,unit:'tsp'},{name:'Black pepper',amount:0.25,unit:'tsp'}],steps:['Bring steak to room temp 30 min, pat dry','Season generously on all sides','Sear in smoking-hot cast iron 3–4 min per side for medium-rare (125°F internal)','Add butter, garlic, and thyme in last 90 seconds — baste constantly','Rest 10 min before slicing thin against the grain'],storage:'Reheat in hot skillet with splash of broth 60–90 seconds. Never microwave.',utensils:['Cast iron pan','Tongs','Meat thermometer']},
  'blackened-salmon': {name:'Blackened salmon',emoji:'🐟',category:'protein',yield:'1 serving',ingredients:[{name:'Salmon fillet',amount:6,unit:'oz'},{name:'Avocado oil',amount:1,unit:'tsp'},{name:'Smoked paprika',amount:1,unit:'tsp'},{name:'Garlic powder',amount:0.5,unit:'tsp'},{name:'Onion powder',amount:0.25,unit:'tsp'},{name:'Cayenne',amount:0.25,unit:'tsp'},{name:'Thyme',amount:0.25,unit:'tsp'},{name:'Salt',amount:0.5,unit:'tsp'}],steps:['Pat salmon dry, coat in spice blend','Heat cast iron very hot, add oil','Cook skin-side up 3–4 min until crust forms','Flip, cook 2–3 min more','Pull when center still slightly translucent — firms up as it rests'],storage:'Best within 2–3 days. Can serve cold over salads.',utensils:['Cast iron pan','Fish spatula']},
  'turkey-taco': {name:'Ground turkey taco meat',emoji:'🫙',category:'protein',yield:'1 serving (5 oz cooked)',ingredients:[{name:'Ground turkey 93/7',amount:6,unit:'oz raw'},{name:'Yellow onion, diced',amount:2,unit:'tbsp'},{name:'Garlic, minced',amount:0.5,unit:'clove'},{name:'Chili powder',amount:0.5,unit:'tsp'},{name:'Cumin',amount:0.25,unit:'tsp'},{name:'Smoked paprika',amount:0.25,unit:'tsp'},{name:'Oregano',amount:0.25,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'},{name:'Chicken broth',amount:1,unit:'tbsp'}],steps:['Heat oil, sauté onion 3 min','Add garlic, cook 30 seconds','Add turkey, break up with spoon, cook 7–8 min until no pink','Add spices and broth, simmer 3–4 min until liquid absorbs','Taste and adjust salt'],storage:'Keeps 4 days. Good cold in salads or reheated.',utensils:['Large skillet','Wooden spoon']},
  'turkey-meatballs': {name:'Turkey meatballs',emoji:'🍖',category:'protein',yield:'1 serving (6 small meatballs)',ingredients:[{name:'Ground turkey 93/7',amount:5,unit:'oz'},{name:'Breadcrumbs',amount:1,unit:'tbsp'},{name:'Egg',amount:0.25,unit:'ea'},{name:'Parmesan, grated',amount:1,unit:'tbsp'},{name:'Garlic, minced',amount:0.5,unit:'clove'},{name:'Italian herbs',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Mix all ingredients gently — don\'t overwork','Form into 6 even meatballs','Bake at 400°F on parchment-lined sheet 18–20 min','Internal temp should reach 165°F'],storage:'Keeps 4 days. Freezes well cooked.',utensils:['Mixing bowl','Baking sheet','Parchment paper']},
  'sauteed-shrimp': {name:'Sautéed shrimp',emoji:'🦐',category:'protein',yield:'1 serving',ingredients:[{name:'Shrimp, peeled & deveined',amount:6,unit:'oz'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Garlic, minced',amount:1,unit:'clove'},{name:'Salt',amount:0.25,unit:'tsp'},{name:'Red pepper flakes',amount:0.125,unit:'tsp'}],steps:['Pat shrimp dry — this is critical for a good sear','Heat pan hot, add oil','Shrimp in single layer, do not crowd, cook 1–2 min per side until pink','Add garlic in last 30 seconds','Finish with red pepper flakes, salt'],storage:'Best day-of. Cooks in 5 min so do fresh.',utensils:['Skillet','Tongs']},
  'cauli-rice': {name:'Cauliflower rice',emoji:'🌾',category:'base',yield:'1 serving (1 cup)',ingredients:[{name:'Cauliflower',amount:0.5,unit:'head'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Garlic, minced',amount:0.5,unit:'clove'},{name:'Scallion, sliced',amount:1,unit:'tbsp'},{name:'Salt',amount:0.25,unit:'tsp'},{name:'White pepper',amount:0.125,unit:'tsp'}],steps:['Cut cauliflower into florets, pulse in food processor until rice-sized (or buy pre-riced)','Heat oil in pan over medium-high','Garlic and scallion, 30 seconds until fragrant','Add cauliflower in thin layer, do not stir for 2 min (lets it brown)','Cook 5–6 min total, stirring occasionally, until tender with golden edges','Season generously'],storage:'Keeps 5 days. Reheats well in pan or microwave.',utensils:['Food processor','Large skillet']},
  'broc-mush': {name:'Roasted broccoli & mushrooms',emoji:'🥦',category:'side',yield:'1 serving',ingredients:[{name:'Broccoli florets',amount:1,unit:'cup'},{name:'Baby bella mushrooms, quartered',amount:0.75,unit:'cup'},{name:'Olive oil',amount:1,unit:'tbsp'},{name:'Garlic powder',amount:0.25,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'},{name:'Black pepper',amount:0.125,unit:'tsp'}],steps:['Preheat oven to 425°F','Toss veggies with oil, garlic powder, salt, pepper','Spread in single layer on sheet pan — do not overcrowd','Roast 22–25 min, flipping once at 12 min','Look for caramelized edges — that\'s the flavor'],storage:'Keeps 4 days. Reheat at 350°F to preserve texture.',utensils:['Baking sheet','Bowl','Spatula']},
  'zucc-pep': {name:'Roasted zucchini & peppers',emoji:'🫑',category:'side',yield:'1 serving',ingredients:[{name:'Zucchini, cubed',amount:0.5,unit:'medium'},{name:'Bell pepper, sliced',amount:0.5,unit:'ea'},{name:'Red onion, sliced',amount:0.25,unit:'ea'},{name:'Olive oil',amount:1,unit:'tbsp'},{name:'Italian herbs',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Preheat oven to 425°F','Cut vegetables to uniform size','Toss with oil, herbs, salt','Single layer on sheet pan','Roast 20–22 min, flipping halfway'],storage:'Keeps 4 days. Great hot or cold.',utensils:['Baking sheet','Bowl']},
  'zucc-noodle': {name:'Zucchini noodles',emoji:'🍜',category:'side',yield:'1 serving',ingredients:[{name:'Zucchini, large',amount:1,unit:'ea'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Salt',amount:1,unit:'pinch'}],steps:['Spiralize zucchini (or use julienne peeler)','Either serve raw cold OR sauté 2–3 min in hot pan','If sautéing, keep it brief — should be just tender, not mushy','Salt right before serving to prevent water release'],storage:'Best fresh or day-of. Raw noodles keep 2 days.',utensils:['Spiralizer','Skillet']},
  'creamed-kale': {name:'Creamed kale & spinach',emoji:'🥬',category:'side',yield:'1 serving',ingredients:[{name:'Lacinato kale, stems removed, chopped',amount:0.5,unit:'bunch'},{name:'Baby spinach',amount:1,unit:'cup'},{name:'Butter',amount:1,unit:'tsp'},{name:'Garlic, minced',amount:1,unit:'clove'},{name:'Heavy cream',amount:2,unit:'tbsp'},{name:'Parmesan, grated',amount:1,unit:'tbsp'},{name:'Ground nutmeg',amount:1,unit:'pinch'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Melt butter in skillet, add garlic, 1 min','Add kale, toss and cook 4–5 min until wilted and tender','Add spinach, cook 1–2 min until just wilted','Add heavy cream, simmer 3 min until slightly thickened','Stir in parmesan and nutmeg off heat'],storage:'Keeps 4 days. Nutmeg is the key — don\'t skip.',utensils:['Skillet','Wooden spoon']},
  'fresh-spinach': {name:'Fresh spinach prep',emoji:'🌿',category:'side',yield:'1 serving (2 cups)',ingredients:[{name:'Baby spinach',amount:2,unit:'cup'}],steps:['Wash thoroughly in cold water','Spin dry or pat with towels','Store in container lined with paper towel','Use within 3 days'],storage:'Keep dry in fridge, 3 days max.',utensils:['Salad spinner']},
  'bok-choy': {name:'Sautéed bok choy',emoji:'🥬',category:'side',yield:'1 serving',ingredients:[{name:'Bok choy, halved',amount:1,unit:'head'},{name:'Olive oil',amount:1,unit:'tsp'},{name:'Garlic, minced',amount:1,unit:'clove'},{name:'Soy sauce',amount:1,unit:'tsp'},{name:'Sesame oil',amount:0.5,unit:'tsp'}],steps:['Heat pan hot, add olive oil','Bok choy cut-side down, 2 min until charred','Flip, add garlic and soy sauce','Cook 1–2 min more until stems just tender','Finish with sesame oil off heat'],storage:'Best day-of. Quick enough to make fresh.',utensils:['Skillet','Tongs']},
  'stuffed-pepper': {name:'Turkey stuffed pepper',emoji:'🫑',category:'side',yield:'1 serving',ingredients:[{name:'Bell pepper, large, halved & seeded',amount:1,unit:'ea'},{name:'Turkey taco meat (pre-cooked)',amount:5,unit:'oz'},{name:'Shredded cheese (optional)',amount:1,unit:'tbsp'}],steps:['Preheat oven to 400°F','Place pepper halves cut-side up on sheet pan','Fill each with cooked turkey','Top with cheese if using','Bake 20–25 min until pepper is tender'],storage:'Keeps 3 days. Reheats well in oven.',utensils:['Baking sheet']},
  'ratatouille': {name:'Ratatouille vegetables',emoji:'🍅',category:'side',yield:'1 serving (1 cup)',ingredients:[{name:'Zucchini, cubed',amount:0.5,unit:'ea'},{name:'Eggplant, cubed',amount:0.5,unit:'cup'},{name:'Bell pepper, diced',amount:0.5,unit:'ea'},{name:'Tomato, diced',amount:0.5,unit:'cup'},{name:'Yellow onion, diced',amount:0.25,unit:'ea'},{name:'Garlic, minced',amount:1,unit:'clove'},{name:'Olive oil',amount:1,unit:'tbsp'},{name:'Herbes de Provence',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Sauté onion in oil 3 min','Add garlic, 30 seconds','Add eggplant, cook 5 min','Add zucchini and peppers, cook 4 min','Stir in tomato and herbs, simmer 10–12 min until soft'],storage:'Keeps 5 days and improves day two.',utensils:['Large pot or Dutch oven']},
  'roasted-mushrooms': {name:'Roasted mushrooms',emoji:'🍄',category:'side',yield:'1 serving',ingredients:[{name:'Baby bella mushrooms, quartered',amount:0.75,unit:'cup'},{name:'Olive oil',amount:2,unit:'tsp'},{name:'Garlic, minced',amount:0.5,unit:'clove'},{name:'Fresh thyme',amount:1,unit:'pinch'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Preheat oven to 425°F','Toss mushrooms with oil, garlic, thyme, salt','Single layer on sheet pan — spacing matters','Roast 18–20 min until deeply browned at edges','Don\'t stir too early, let them caramelize'],storage:'Keeps 4 days.',utensils:['Baking sheet','Bowl']},
  'bell-pepper-salad': {name:'Bell pepper + side salad',emoji:'🥗',category:'side',yield:'1 serving',ingredients:[{name:'Bell pepper, large',amount:1,unit:'ea'},{name:'Mixed greens',amount:1,unit:'cup'},{name:'Cucumber, sliced',amount:0.25,unit:'cup'},{name:'Cherry tomatoes, halved',amount:0.25,unit:'cup'},{name:'Olive oil + lemon',amount:1,unit:'drizzle'}],steps:['Prep bell pepper (roast or stuff separately)','Toss greens, cucumber, tomato in a bowl','Drizzle with olive oil and lemon just before serving'],storage:'Dress salad day-of. Greens keep 3 days undressed.',utensils:['Bowl']},
  'chimichurri': {name:'Chimichurri sauce',emoji:'🌿',category:'sauce',yield:'Makes ~1 cup (8 servings)',yieldCount:8,ingredients:[{name:'Flat-leaf parsley, packed',amount:1,unit:'cup'},{name:'Fresh oregano (or 1 tsp dried)',amount:2,unit:'tbsp'},{name:'Garlic, minced',amount:3,unit:'clove'},{name:'Olive oil',amount:0.5,unit:'cup'},{name:'Red wine vinegar',amount:2,unit:'tbsp'},{name:'Red pepper flakes',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.5,unit:'tsp'}],steps:['Finely chop parsley, oregano, and garlic by hand (food processor makes it too paste-like)','Combine with oil, vinegar, red pepper flakes, salt','Stir well, taste and adjust acid or salt','Let sit 30 min before using — flavor develops'],storage:'Keeps 1 week refrigerated. Bring to room temp before serving.',utensils:['Knife','Glass jar']},
  'dijon': {name:'Creamy Dijon sauce',emoji:'🫙',category:'sauce',yield:'Makes ~1 cup (6 servings)',yieldCount:6,ingredients:[{name:'Butter',amount:2,unit:'tbsp'},{name:'Garlic, minced',amount:2,unit:'clove'},{name:'Dijon mustard',amount:1,unit:'tbsp'},{name:'Beef broth',amount:0.25,unit:'cup'},{name:'Heavy cream',amount:0.25,unit:'cup'},{name:'Fresh thyme',amount:0.5,unit:'tsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Melt butter in small saucepan over medium','Add garlic, cook 1 min until fragrant','Stir in Dijon to coat','Add beef broth, scrape up any bits, simmer 2 min','Add cream and thyme, simmer 5–7 min until slightly thickened','Season with salt'],storage:'Keeps 5 days. Reheat gently, do not boil or cream will split.',utensils:['Small saucepan','Whisk']},
  'tomato-basil': {name:'Creamy tomato basil',emoji:'🍅',category:'sauce',yield:'Makes ~2 cups (8 servings)',yieldCount:8,ingredients:[{name:'Butter',amount:1,unit:'tbsp'},{name:'Garlic, minced',amount:2,unit:'clove'},{name:'Crushed tomatoes',amount:14,unit:'oz can'},{name:'Red pepper flakes',amount:1,unit:'pinch'},{name:'Heavy cream',amount:0.25,unit:'cup'},{name:'Parmesan, grated',amount:2,unit:'tbsp'},{name:'Fresh basil, chopped',amount:0.25,unit:'cup'},{name:'Salt',amount:0.5,unit:'tsp'}],steps:['Melt butter in saucepan, add garlic, cook 2 min','Add crushed tomatoes and red pepper flakes, simmer 10 min','Lower heat, stir in cream and parmesan','Simmer 3–4 min until thickened','Remove from heat, stir in basil'],storage:'Keeps 5 days. Freezes well (without the cream — add when reheating).',utensils:['Saucepan']},
  'garlic-butter': {name:'Garlic butter sauce',emoji:'🧈',category:'sauce',yield:'Makes ~½ cup (4 servings)',yieldCount:4,ingredients:[{name:'Butter',amount:3,unit:'tbsp'},{name:'Garlic, minced',amount:2,unit:'clove'},{name:'Lemon juice',amount:1,unit:'tsp'},{name:'Fresh parsley, chopped',amount:1,unit:'tbsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Melt butter on low heat — do not brown','Add garlic, cook 1 min until fragrant','Off heat, stir in lemon, parsley, salt','Use immediately or keep warm'],storage:'Best fresh. Can freeze in portions and remelt.',utensils:['Small saucepan']},
  'lemon-herb': {name:'Lemon herb dressing',emoji:'🍋',category:'sauce',yield:'Makes ~½ cup (4 servings)',yieldCount:4,ingredients:[{name:'Olive oil',amount:0.25,unit:'cup'},{name:'Lemon juice',amount:2,unit:'tbsp'},{name:'Dijon mustard',amount:0.5,unit:'tsp'},{name:'Garlic, grated',amount:0.5,unit:'clove'},{name:'Fresh parsley, chopped',amount:1,unit:'tbsp'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Whisk all ingredients in a bowl, or shake in a jar','Taste and adjust — should be bright and balanced'],storage:'Keeps 5 days refrigerated. Shake before using.',utensils:['Jar or Whisk']},
  'herb-oil': {name:'Herb olive oil drizzle',emoji:'🫒',category:'sauce',yield:'Makes ~⅓ cup (4 servings)',yieldCount:4,ingredients:[{name:'Olive oil',amount:3,unit:'tbsp'},{name:'Garlic, smashed',amount:1,unit:'clove'},{name:'Mixed dried herbs',amount:1,unit:'tsp'},{name:'Lemon zest',amount:0.5,unit:'tsp'},{name:'Salt',amount:1,unit:'pinch'}],steps:['Warm oil gently with smashed garlic 2 min (do not brown)','Off heat, add herbs and lemon zest','Let infuse 10 min','Drizzle at serving'],storage:'Keeps 1 week. Strain out garlic if saving longer.',utensils:['Small pan']},
  'pico': {name:'Pico de gallo',emoji:'🍅',category:'sauce',yield:'Makes ~1 cup (4 servings)',yieldCount:4,ingredients:[{name:'Roma tomato, diced',amount:1,unit:'medium'},{name:'Red onion, finely diced',amount:2,unit:'tbsp'},{name:'Jalapeño, minced',amount:0.5,unit:'ea'},{name:'Fresh cilantro, chopped',amount:2,unit:'tbsp'},{name:'Lime juice',amount:1,unit:'ea'},{name:'Salt',amount:0.25,unit:'tsp'}],steps:['Dice everything to uniform size','Combine in bowl with lime and salt','Let sit 10 min for flavors to meld','Drain any excess liquid before serving'],storage:'Best within 3 days. Drains more as it sits.',utensils:['Knife','Bowl']},
};

export const CLIENT_COLORS = [
  {bg:'#ECF5E0',fg:'#1E4F06'},
  {bg:'#E4EFFC',fg:'#1055A5'},
  {bg:'#FAE9F2',fg:'#8C2560'},
  {bg:'#FFF0D6',fg:'#7A4500'},
  {bg:'#E0F4F0',fg:'#0A5E4A'},
  {bg:'#FAE8E4',fg:'#8C2A18'}
];
